import { exportToExcel } from './exportUtils';

export const generateWeeklySummaryData = (collections, startDateStr, endDateStr) => {
  // Filter collections by date range
  const filtered = collections.filter(c => 
    c.collection_date >= startDateStr && c.collection_date <= endDateStr
  );

  const customerMap = {};

  filtered.forEach(c => {
    if (!customerMap[c.customer_id]) {
      customerMap[c.customer_id] = {
        customer_id: c.customer_id,
        customer_name: c.customer_name,
        mCow: 0,
        mBuf: 0,
        eCow: 0,
        eBuf: 0,
        cowAmt: 0,
        bufAmt: 0,
      };
    }

    const row = customerMap[c.customer_id];
    if (c.shift === 'Morning') {
      if (c.milk_type === 'Cow') {
        row.mCow += c.quantity;
        row.cowAmt += c.total_amount;
      } else {
        row.mBuf += c.quantity;
        row.bufAmt += c.total_amount;
      }
    } else {
      if (c.milk_type === 'Cow') {
        row.eCow += c.quantity;
        row.cowAmt += c.total_amount;
      } else {
        row.eBuf += c.quantity;
        row.bufAmt += c.total_amount;
      }
    }
  });

  const weeklyRows = Object.values(customerMap).map(row => {
    const totalCow = row.mCow + row.eCow;
    const totalBuf = row.mBuf + row.eBuf;
    const grandLiters = totalCow + totalBuf;
    const grandAmount = row.cowAmt + row.bufAmt;

    return {
      customer_id: row.customer_id,
      customer_name: row.customer_name,
      mCow: parseFloat(row.mCow.toFixed(2)),
      mBuf: parseFloat(row.mBuf.toFixed(2)),
      eCow: parseFloat(row.eCow.toFixed(2)),
      eBuf: parseFloat(row.eBuf.toFixed(2)),
      totalCow: parseFloat(totalCow.toFixed(2)),
      totalBuf: parseFloat(totalBuf.toFixed(2)),
      grandLiters: parseFloat(grandLiters.toFixed(2)),
      cowAmt: parseFloat(row.cowAmt.toFixed(2)),
      bufAmt: parseFloat(row.bufAmt.toFixed(2)),
      grandAmount: parseFloat(grandAmount.toFixed(2))
    };
  });

  return weeklyRows;
};

export const sendWeeklyWhatsAppReport = (collections, startDateStr, endDateStr, phone = '') => {
  const weeklyData = generateWeeklySummaryData(collections, startDateStr, endDateStr);
  
  const totalLiters = weeklyData.reduce((a, c) => a + c.grandLiters, 0);
  const totalAmount = weeklyData.reduce((a, c) => a + c.grandAmount, 0);

  // 1. Download Excel Sheet
  const filename = `MilkCollection_${startDateStr}_to_${endDateStr}.xlsx`;
  const excelFormat = weeklyData.map(w => ({
    'Customer ID': w.customer_id,
    'Customer Name': w.customer_name,
    'Morning Cow Milk (L)': w.mCow,
    'Morning Buffalo Milk (L)': w.mBuf,
    'Evening Cow Milk (L)': w.eCow,
    'Evening Buffalo Milk (L)': w.eBuf,
    'Total Cow Milk (L)': w.totalCow,
    'Total Buffalo Milk (L)': w.totalBuf,
    'Grand Total Liters': w.grandLiters,
    'Cow Milk Amount (₹)': w.cowAmt,
    'Buffalo Milk Amount (₹)': w.bufAmt,
    'Grand Total Amount (₹)': w.grandAmount
  }));
  
  exportToExcel(excelFormat, filename);

  // 2. Generate WhatsApp Text
  const msgText = 
`*Weekly Milk Collection Report* 🥛
*Week:* ${startDateStr} - ${endDateStr}

*Summary:*
• Total Registered Farmers: ${weeklyData.length}
• Total Liters Collected: ${totalLiters.toFixed(2)} L
• Total Payout Amount: ₹${totalAmount.toFixed(2)}

*Attached File:* ${filename}
(Note: File has been saved to your downloads folder)

_Generated by Milkman Collection App_`;

  const encoded = encodeURIComponent(msgText);
  let whatsappUrl = `https://api.whatsapp.com/send?text=${encoded}`;
  if (phone) {
    const cleanPhone = phone.replace(/[^0-9]/g, '');
    whatsappUrl = `https://api.whatsapp.com/send?phone=${cleanPhone}&text=${encoded}`;
  }

  window.open(whatsappUrl, '_blank');
};
