import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useApp } from '../context/AppContext';
import { UserPlus, User, Phone, MapPin, FileText, CheckCircle2, ArrowLeft } from 'lucide-react';

export const WomanRegistration = () => {
  const { customers, addCustomer } = useApp();
  const navigate = useNavigate();

  const nextSeq = customers.length ? (Math.max(...customers.map(c => parseInt(c.id.replace('M', '')) || 0)) + 1) : 1;
  const autoGeneratedId = 'M' + String(nextSeq).padStart(4, '0');

  const [name, setName] = useState('');
  const [phone, setPhone] = useState('');
  const [address, setAddress] = useState('');
  const [notes, setNotes] = useState('');
  const [submitting, setSubmitting] = useState(false);

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!name.trim()) return;

    setSubmitting(true);
    const res = await addCustomer({
      name: name.trim(),
      phone: phone.trim(),
      address: address.trim(),
      notes: notes.trim()
    });
    setSubmitting(false);

    if (res.success && res.customer) {
      // Redirect to Milk Collection with new woman auto-selected
      navigate(`/collect?customerId=${res.customer.id}`);
    }
  };

  return (
    <div className="max-w-xl mx-auto space-y-6 pb-20 sm:pb-8">
      
      {/* Header */}
      <div className="card-glass p-5 border-purple-500/30 flex items-center justify-between">
        <div>
          <h1 className="text-xl sm:text-2xl font-black text-slate-900 dark:text-slate-100 flex items-center gap-2">
            <UserPlus className="w-6 h-6 text-purple-500" />
            <span>Add New Woman Farmer</span>
          </h1>
          <p className="text-xs text-slate-500 font-semibold">
            Register new woman supplier for daily milk collection
          </p>
        </div>
        <button
          onClick={() => navigate(-1)}
          className="p-2 rounded-xl bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-300 hover:bg-slate-200"
        >
          <ArrowLeft className="w-5 h-5" />
        </button>
      </div>

      {/* Auto-Generated Customer ID Banner */}
      <div className="p-4 bg-purple-500/10 dark:bg-purple-950/40 border border-purple-500/30 rounded-2xl flex items-center justify-between">
        <div>
          <span className="text-[11px] font-extrabold uppercase tracking-wider text-purple-700 dark:text-purple-300 block">
            Auto-Generated Customer ID
          </span>
          <div className="text-2xl font-black text-purple-600 dark:text-purple-400 font-mono">
            {autoGeneratedId}
          </div>
        </div>
        <span className="text-xs text-purple-600 dark:text-purple-300 font-semibold bg-purple-100 dark:bg-purple-900/60 px-3 py-1 rounded-xl">
          Auto Assigned
        </span>
      </div>

      {/* Form Card */}
      <form onSubmit={handleSubmit} className="card-glass p-6 space-y-5">
        
        {/* Woman Name */}
        <div>
          <label className="block text-xs font-extrabold text-slate-600 dark:text-slate-400 uppercase tracking-wider mb-2">
            Woman Name <span className="text-rose-500">*</span>
          </label>
          <div className="relative">
            <User className="absolute left-4 top-3.5 w-5 h-5 text-slate-400" />
            <input
              type="text"
              value={name}
              onChange={(e) => setName(e.target.value)}
              placeholder="e.g. Lakshmi, Lakshmipriya..."
              className="w-full pl-12 pr-4 py-3 bg-slate-50 dark:bg-slate-950 border border-slate-300 dark:border-slate-700 rounded-xl text-base font-bold text-slate-900 dark:text-slate-100 focus:ring-2 focus:ring-purple-500 outline-none"
              required
            />
          </div>
        </div>

        {/* Mobile Number */}
        <div>
          <label className="block text-xs font-extrabold text-slate-600 dark:text-slate-400 uppercase tracking-wider mb-2">
            Mobile Number (Optional)
          </label>
          <div className="relative">
            <Phone className="absolute left-4 top-3.5 w-5 h-5 text-slate-400" />
            <input
              type="tel"
              value={phone}
              onChange={(e) => setPhone(e.target.value)}
              placeholder="e.g. 9876543210"
              className="w-full pl-12 pr-4 py-3 bg-slate-50 dark:bg-slate-950 border border-slate-300 dark:border-slate-700 rounded-xl text-base font-semibold text-slate-900 dark:text-slate-100 focus:ring-2 focus:ring-purple-500 outline-none"
            />
          </div>
        </div>

        {/* Address */}
        <div>
          <label className="block text-xs font-extrabold text-slate-600 dark:text-slate-400 uppercase tracking-wider mb-2">
            Address (Optional)
          </label>
          <div className="relative">
            <MapPin className="absolute left-4 top-3.5 w-5 h-5 text-slate-400" />
            <input
              type="text"
              value={address}
              onChange={(e) => setAddress(e.target.value)}
              placeholder="e.g. Village East Gate, House #12"
              className="w-full pl-12 pr-4 py-3 bg-slate-50 dark:bg-slate-950 border border-slate-300 dark:border-slate-700 rounded-xl text-base font-semibold text-slate-900 dark:text-slate-100 focus:ring-2 focus:ring-purple-500 outline-none"
            />
          </div>
        </div>

        {/* Notes */}
        <div>
          <label className="block text-xs font-extrabold text-slate-600 dark:text-slate-400 uppercase tracking-wider mb-2">
            Notes (Optional)
          </label>
          <div className="relative">
            <FileText className="absolute left-4 top-3.5 w-5 h-5 text-slate-400" />
            <textarea
              value={notes}
              onChange={(e) => setNotes(e.target.value)}
              placeholder="e.g. Primary cow milk supplier, morning shift regular"
              rows={3}
              className="w-full pl-12 pr-4 py-3 bg-slate-50 dark:bg-slate-950 border border-slate-300 dark:border-slate-700 rounded-xl text-sm font-semibold text-slate-900 dark:text-slate-100 focus:ring-2 focus:ring-purple-500 outline-none"
            />
          </div>
        </div>

        {/* Submit */}
        <button
          type="submit"
          disabled={submitting || !name.trim()}
          className="w-full btn-touch min-h-[56px] bg-purple-600 hover:bg-purple-500 text-white font-extrabold text-base rounded-2xl shadow-lg shadow-purple-600/30 active:scale-95 transition-all flex items-center justify-center gap-2"
        >
          <CheckCircle2 className="w-5 h-5" />
          <span>{submitting ? 'Saving Woman Profile...' : 'Save & Start Milk Collection →'}</span>
        </button>

      </form>

    </div>
  );
};
